export const collectionsData = {
  hoodies: {
    title: 'Hoodies',
    description:
      'Premium coats designed to keep you warm and stylish during the colder months.',
    items: [
      {
        id: '1',
        name: 'Classic Zipper Hoodie',
        price: '₹498.00',
        originalPrice: '₹688.00',
        discount: '6% OFF',
        description:
          "Our men's brown long coat is the perfect addition to any gentleman's wardrobe. Made with high-quality materials, this coat is designed to keep you warm and stylish during the colder months. The classic brown color and timeless design make it a versatile piece that can be dressed up or down for any occasion.",
        features: [
          'High-quality materials for durability and comfort',
          'Classic notch lapel collar and single-breasted button closure',
          'Two front pockets for convenient storage or hand warming',
          'Long length provides excellent coverage and warmth',
          'Flattering fit for all body types',
        ],
        colors: ['coffee', 'darkbrown', 'olive', 'tan', 'black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 5.0,
        reviews: 1,
        images: ['/images/collections/hoodies/hoodie_zipper_black.webp'],
      },
      {
        id: '2',
        name: 'Classic Lavender Hoodie',
        price: '₹498.00',
        originalPrice: '₹688.00',
        discount: '6% OFF',
        description:
          "Our men's brown long coat is the perfect addition to any gentleman's wardrobe. Made with high-quality materials, this coat is designed to keep you warm and stylish during the colder months. The classic brown color and timeless design make it a versatile piece that can be dressed up or down for any occasion.",
        features: [
          'High-quality materials for durability and comfort',
          'Classic notch lapel collar and single-breasted button closure',
          'Two front pockets for convenient storage or hand warming',
          'Long length provides excellent coverage and warmth',
          'Flattering fit for all body types',
        ],
        colors: ['coffee', 'darkbrown', 'olive', 'tan', 'black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 5.0,
        reviews: 1,
        images: ['/images/collections/hoodies/hoodie_lavender.webp'],
      },
      {
        id: '3',
        name: 'Classic Navy Hoodie',
        price: '₹498.00',
        originalPrice: '₹688.00',
        discount: '6% OFF',
        description:
          "Our men's brown long coat is the perfect addition to any gentleman's wardrobe. Made with high-quality materials, this coat is designed to keep you warm and stylish during the colder months. The classic brown color and timeless design make it a versatile piece that can be dressed up or down for any occasion.",
        features: [
          'High-quality materials for durability and comfort',
          'Classic notch lapel collar and single-breasted button closure',
          'Two front pockets for convenient storage or hand warming',
          'Long length provides excellent coverage and warmth',
          'Flattering fit for all body types',
        ],
        colors: ['coffee', 'darkbrown', 'olive', 'tan', 'black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 5.0,
        reviews: 1,
        images: ['/images/collections/hoodies/hoodie_navy.webp'],
      },
      {
        id: '4',
        name: 'Classic Olive Green Hoodie',
        price: '₹498.00',
        originalPrice: '₹688.00',
        discount: '6% OFF',
        description:
          "Our men's brown long coat is the perfect addition to any gentleman's wardrobe. Made with high-quality materials, this coat is designed to keep you warm and stylish during the colder months. The classic brown color and timeless design make it a versatile piece that can be dressed up or down for any occasion.",
        features: [
          'High-quality materials for durability and comfort',
          'Classic notch lapel collar and single-breasted button closure',
          'Two front pockets for convenient storage or hand warming',
          'Long length provides excellent coverage and warmth',
          'Flattering fit for all body types',
        ],
        colors: ['coffee', 'darkbrown', 'olive', 'tan', 'black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 5.0,
        reviews: 1,
        images: ['/images/collections/hoodies/hoodie_olive1.webp'],
      },
      {
        id: '5',
        name: 'Classic Verdigris Blue Hoodie',
        price: '₹489.99',
        originalPrice: '₹209.99',
        discount: '10% OFF',
        description:
          'A timeless trench coat that never goes out of style. Perfect for transitional weather and professional settings.',
        features: [
          'Water-resistant fabric',
          'Adjustable belt',
          'Interior pockets',
          'Classic double-breasted design',
          'Removable liner for seasonal versatility',
        ],
        colors: ['beige', 'black', 'navy'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 4.8,
        reviews: 24,
        images: ['/images/collections/hoodies/hoodie_olive.webp'],
      },
    ],
  },
  tshirts: {
    title: 'T-Shirts',
    description:
      'Explore our range of stylish t-shirts in various colors and designs.',
    items: [
      {
        id: '1',
        name: 'Basic White T-Shirt',
        price: '₹239',
        originalPrice: '₹699',
        discount: '20% OFF',
        description:
          'A comfortable and versatile white t-shirt made from premium cotton.',
        features: [
          '100% organic cotton',
          'Breathable fabric',
          'Regular fit',
          'Crew neck',
          'Easy to style',
        ],
        colors: ['white', 'black', 'gray', 'navy', 'red'],
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        rating: 4.5,
        reviews: 42,
        images: ['/images/collections/tshirts/tshirt_graphic.webp'],
      },
      {
        id: '2',
        name: 'Graphic Tee',
        price: '₹239',
        originalPrice: '₹699',
        discount: '13% OFF',
        description:
          'Express your personality with our unique graphic tee designs.',
        features: [
          'Soft cotton blend',
          'Durable print',
          'Pre-shrunk fabric',
          'Relaxed fit',
          'Unisex design',
        ],
        colors: ['black', 'white', 'gray'],
        sizes: ['S', 'M', 'L', 'XL'],
        rating: 4.7,
        reviews: 18,
        images: ['/images/collections/tshirts/tshirt_believe-in-yourself.webp'],
      },
    ],
  },
  sweatshirts: {
    title: 'Sweat-Shirts',
    description:
      'Find the best Sweat-Shirt for work, casual, and formal occasions.',
    items: [
      {
        id: '1',
        name: 'Slim lavender Sweat-Shirt',
        price: '₹49.99',
        originalPrice: '₹59.99',
        discount: '17% OFF',
        description:
          'Elegant slim fit sweat-shirt perfect for formal and business occasions.',
        features: [
          'Wrinkle-resistant fabric',
          'Slim fit design',
          'Hidden stretch for comfort',
          'Side and back pockets',
          'Belt loops',
        ],
        colors: ['black', 'navy', 'charcoal', 'beige'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.6,
        reviews: 35,
        images: ['/images/collections/sweatshirts/sweatshirt_lavender.webp'],
      },
      {
        id: '2',
        name: 'Slim Powder Blue Sweat-Shirt',
        price: '₹39.99',
        originalPrice: '₹45.99',
        discount: '13% OFF',
        description:
          'Versatile chino pants that transition seamlessly from casual to semi-formal settings.',
        features: [
          'Cotton twill fabric',
          'Regular fit',
          'Flat front design',
          'Slash pockets',
          'Versatile styling options',
        ],
        colors: ['khaki', 'navy', 'olive', 'burgundy', 'gray'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.4,
        reviews: 27,
        images: [
          '/images/collections/sweatshirts/sweat_shirt_powder_blue.webp',
        ],
      },
      {
        id: '3',
        name: 'Slim Sweat-Shirt',
        price: '₹39.99',
        originalPrice: '₹45.99',
        discount: '13% OFF',
        description:
          'Versatile chino pants that transition seamlessly from casual to semi-formal settings.',
        features: [
          'Cotton twill fabric',
          'Regular fit',
          'Flat front design',
          'Slash pockets',
          'Versatile styling options',
        ],
        colors: ['khaki', 'navy', 'olive', 'burgundy', 'gray'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.4,
        reviews: 27,
        images: ['/images/collections/sweatshirts/sweatshirt_mocha.webp'],
      },
      {
        id: '4',
        name: 'Slim Sweat-Shirt',
        price: '₹39.99',
        originalPrice: '₹45.99',
        discount: '13% OFF',
        description:
          'Versatile chino pants that transition seamlessly from casual to semi-formal settings.',
        features: [
          'Cotton twill fabric',
          'Regular fit',
          'Flat front design',
          'Slash pockets',
          'Versatile styling options',
        ],
        colors: ['khaki', 'navy', 'olive', 'burgundy', 'gray'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.4,
        reviews: 27,
        images: ['/images/collections/sweatshirts/sweatshirt_navy_blue.webp'],
      },
      {
        id: '5',
        name: 'Slim Sweat-Shirt',
        price: '₹39.99',
        originalPrice: '₹45.99',
        discount: '13% OFF',
        description:
          'Versatile chino pants that transition seamlessly from casual to semi-formal settings.',
        features: [
          'Cotton twill fabric',
          'Regular fit',
          'Flat front design',
          'Slash pockets',
          'Versatile styling options',
        ],
        colors: ['khaki', 'navy', 'olive', 'burgundy', 'gray'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.4,
        reviews: 27,
        images: [
          '/images/collections/sweatshirts/sweatshirt_verdigris_blue.webp',
        ],
      },
      {
        id: '6',
        name: 'Slim Sweat-Shirt',
        price: '₹39.99',
        originalPrice: '₹45.99',
        discount: '13% OFF',
        description:
          'Versatile chino pants that transition seamlessly from casual to semi-formal settings.',
        features: [
          'Cotton twill fabric',
          'Regular fit',
          'Flat front design',
          'Slash pockets',
          'Versatile styling options',
        ],
        colors: ['khaki', 'navy', 'olive', 'burgundy', 'gray'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.4,
        reviews: 27,
        images: ['/images/collections/sweatshirts/sweatshirt_lavender.webp'],
      },
    ],
  },
  pants: {
    title: 'Jumpsuits',
    description: 'Comfortable and stylish pants for every occasion.',
    items: [
      {
        id: '1',
        name: 'Denim Jeans',
        price: '₹59.99',
        originalPrice: '₹69.99',
        discount: '14% OFF',
        description:
          'Classic denim jeans with a modern fit and premium quality construction.',
        features: [
          'Premium denim fabric',
          'Straight leg fit',
          'Five-pocket design',
          'Reinforced stitching',
          'Versatile styling options',
        ],
        colors: ['blue', 'black', 'gray', 'light-wash'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.8,
        reviews: 56,
        images: [
          '/images/showcaseCategory/sc6.jpg',
          '/images/showcaseCategory/sc6.jpg',
          '/images/showcaseCategory/sc6.jpg',
          '/images/showcaseCategory/sc6.jpg',
          '/images/showcaseCategory/sc6.jpg',
          '/images/showcaseCategory/sc6.jpg',
        ],
      },
      {
        id: '2',
        name: 'Cargo Pants',
        price: '₹45.99',
        originalPrice: '₹55.99',
        discount: '18% OFF',
        description:
          'Functional cargo pants with multiple pockets for practicality and style.',
        features: [
          'Durable cotton blend',
          'Multiple cargo pockets',
          'Relaxed fit',
          'Adjustable waistband',
          'Reinforced knees',
        ],
        colors: ['olive', 'khaki', 'black', 'gray', 'navy'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.3,
        reviews: 31,
        images: [
          '/images/showcaseCategory/sc6.jpg',
          '/images/showcaseCategory/sc6.jpg',
          '/images/showcaseCategory/sc6.jpg',
          '/images/showcaseCategory/sc6.jpg',
          '/images/showcaseCategory/sc6.jpg',
          '/images/showcaseCategory/sc6.jpg',
        ],
      },
    ],
  },
};
